file(GLOB SOURCES CONFIGURE_DEPENDS "*.cpp" "*.h")

add_library(${SPARKIUM_RAYTRACING_SUBLIB_NAME} ${SOURCES} ../../../cpu/cpu_bvh.cpp)

target_link_libraries(${SPARKIUM_RAYTRACING_SUBLIB_NAME} PUBLIC sparkium_backend Grassland Snowberg sparkium_core)
list(APPEND SPARKIUM_RAYTRACING_LIBS ${SPARKIUM_RAYTRACING_SUBLIB_NAME})
set(SPARKIUM_RAYTRACING_LIBS ${SPARKIUM_RAYTRACING_LIBS} PARENT_SCOPE)
