# Adapt the pinned upstream backends in the build tree, without changing the
# ImGui submodule or its public vertex ABI. Fail on upstream layout changes.
function(replace_backend_text OLD NEW)
    string(FIND "${BACKEND_SOURCE}" "${OLD}" MATCH_POSITION)
    if (MATCH_POSITION EQUAL -1)
        message(FATAL_ERROR "ImGui ${BACKEND} float vertex adapter needs updating: ${OLD}")
    endif ()
    string(REPLACE "${OLD}" "${NEW}" BACKEND_SOURCE "${BACKEND_SOURCE}")
    set(BACKEND_SOURCE "${BACKEND_SOURCE}" PARENT_SCOPE)
endfunction()

function(make_float_vertex_backend BACKEND EXTENSION OUTPUT)
    set(INPUT "${LONGMARCH_IMGUI_DIR}/backends/imgui_impl_${BACKEND}.${EXTENSION}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${INPUT}")
    file(READ "${INPUT}" BACKEND_SOURCE)
    replace_backend_text("ImDrawVert" "grassland::imgui::GPUVertex")
    if (BACKEND STREQUAL "metal")
        replace_backend_text("memcpy((char*)vertexBuffer.buffer.contents + vertexBufferOffset, draw_list->VtxBuffer.Data, (size_t)draw_list->VtxBuffer.Size * sizeof(grassland::imgui::GPUVertex));"
            "grassland::imgui::UploadVertices((char*)vertexBuffer.buffer.contents + vertexBufferOffset, draw_list->VtxBuffer.Data, draw_list->VtxBuffer.Size);")
        replace_backend_text("MTLVertexFormatUChar4" "MTLVertexFormatFloat4")
        replace_backend_text("uchar4 color" "float4 color")
        replace_backend_text("float4(in.color) / float4(255.0)" "in.color")
    else ()
        replace_backend_text("memcpy(vtx_dst, draw_list->VtxBuffer.Data, draw_list->VtxBuffer.Size * sizeof(grassland::imgui::GPUVertex));"
            "grassland::imgui::UploadVertices(vtx_dst, draw_list->VtxBuffer.Data, draw_list->VtxBuffer.Size);")
        if (BACKEND STREQUAL "dx12")
            replace_backend_text("\"COLOR\",    0, DXGI_FORMAT_R8G8B8A8_UNORM" "\"COLOR\",    0, DXGI_FORMAT_R32G32B32A32_FLOAT")
        else ()
            replace_backend_text("attribute_desc[2].format = VK_FORMAT_R8G8B8A8_UNORM;" "attribute_desc[2].format = VK_FORMAT_R32G32B32A32_SFLOAT;")
        endif ()
    endif ()
    set(GENERATED "${CMAKE_CURRENT_BINARY_DIR}/imgui_impl_${BACKEND}.${EXTENSION}")
    file(WRITE "${GENERATED}" "#include \"grassland/imgui/vertex_upload.h\"\n${BACKEND_SOURCE}")
    set(${OUTPUT} "${GENERATED}" PARENT_SCOPE)
endfunction()
