file(GLOB SOURCES "*.cpp" "*.h")

add_library(${SPARKIUM_CUDA_TRACING_SUBLIB_NAME} ${SOURCES})

target_link_libraries(${SPARKIUM_CUDA_TRACING_SUBLIB_NAME} PUBLIC sparkium_backend Grassland Snowberg sparkium_cuda_tracing_core sparkium_geometry)
list(APPEND SPARKIUM_CUDA_TRACING_LIBS ${SPARKIUM_CUDA_TRACING_SUBLIB_NAME})
set(SPARKIUM_CUDA_TRACING_LIBS ${SPARKIUM_CUDA_TRACING_LIBS} PARENT_SCOPE)
